variables:
  MY_SCONSTRUCT_LOCATION: $CI_PROJECT_DIR/SConstruct
  MY_PACKAGE_DIR: /tmp/package
  MY_SCONS_DEBUGLOG_YML: $CI_PROJECT_DIR/debuglog.yml

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
default:
  image:
    name: instituteforsoftware/coast-build:latest
    entrypoint: ["/entrypoint.sh", "gosu", "docky"]
  before_script:
  - echo "Running as user [$(id -u)] on hostname [$(hostname)]"
  - python -V               # Print out python version for debugging
  - type -fP tox || pip install tox
  - sudo apt update
  - sudo apt install --no-install-recommends --yes --quiet bats

#build:
#  stage: build
#  tags:
#  - docker
#  script:
#  - tox -l

test:
  stage: test
  tags:
  - docker
  variables:
  artifacts:
    paths:
  script:
  - tox

deploy:
  stage: deploy
  tags:
  - docker
  variables:
    MY_PACKAGE_DIR: $CI_PROJECT_DIR/package
  only:
  - tags
  - triggers
  dependencies:
  script:
  - tox -e deploy
