# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
default:
  image:
    name: instituteforsoftware/coast-build:latest
    entrypoint: ["/entrypoint.sh", "gosu", "docky"]
  before_script:
  - echo "Running as user [$(id -u)] on hostname [$(hostname)]"
  - python -V               # Print out python version for debugging
  - which tox || pip install tox
  - tox --version
  - which bats || sudo npm -i --global bats
  - bats --version
  - which shellcheck || curl -sSL https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz | sudo tar xJf - -C /usr/local/bin --strip-components=1
  - shellcheck --version

#build:
#  stage: build
#  tags:
#  - docker
#  script:
#  - tox -l

test:
  stage: test
  tags:
  - docker
  variables:
  artifacts:
    paths:
  script:
  - tox
